class SplashTemplates {
  static String splashScreenSource({
    required String backgroundColorHex,
    required String iconAssetPath,
  }) {
    final oneLineImage =
        "          child: Image.asset('$iconAssetPath', fit: BoxFit.contain),";
    final imageExpr = oneLineImage.length <= 80
        ? oneLineImage
        : '''          child: Image.asset(
            '$iconAssetPath',
            fit: BoxFit.contain,
          ),''';

    return '''import 'package:flutter/material.dart';

/// A full-screen Splash background with a centered application icon,
/// generated by `smartwork splash`/`smartwork_splash_add`. Deliberately
/// just a [StatelessWidget] — no timer, no navigation, no persistence,
/// no state of any kind. Place it wherever your app needs an initial
/// visual (e.g. as `MaterialApp.home`, or inside your own onboarding
/// flow); this widget never decides that for you.
class SplashScreen extends StatelessWidget {
  const SplashScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF$backgroundColorHex),
      body: Center(
        child: FractionallySizedBox(
          widthFactor: 0.6,
$imageExpr
        ),
      ),
    );
  }
}
''';
  }

  static String splashScreenTestSource({
    required String projectName,
    required String backgroundColorHex,
  }) {
    return '''import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:$projectName/shared/ui/splash_screen.dart';

void main() {
  testWidgets('SplashScreen shows the configured background and a '
      'centered image at 60% of the available width', (tester) async {
    await tester.pumpWidget(const MaterialApp(home: SplashScreen()));

    final scaffold = tester.widget<Scaffold>(find.byType(Scaffold));
    expect(scaffold.backgroundColor, const Color(0xFF$backgroundColorHex));

    expect(find.byType(Image), findsOneWidget);

    final fractionallySizedBox = tester.widget<FractionallySizedBox>(
      find.byType(FractionallySizedBox),
    );
    expect(fractionallySizedBox.widthFactor, 0.6);

    final image = tester.widget<Image>(find.byType(Image));
    expect(image.fit, BoxFit.contain);
  });
}
''';
  }
}
