name: smartwork_cli
description: smartwork_cli package generate the app floder structure.

version: 0.0.1
repository: https://github.com/mskathirravan/smartwork_cli

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2
  cli_dialog: ^0.5.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  process_run: ^0.13.3
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - lib/src/assets/default_yaml/
    - lib/src/assets/images/
