import 'dart:io';

import 'package:smartwork_cli/src/version.dart';
import 'package:test/test.dart';

/// Regression test for a real bug found during this milestone's E2E
/// validation: `smartwork doctor` is meant to run from an arbitrary
/// project directory, and [readSmartworkCliVersion] originally trusted
/// *any* `pubspec.yaml` found relative to the current working
/// directory — so running `doctor` inside a real generated SmartWork
/// project reported *that project's* version (e.g. `1.0.0+1`) as if it
/// were SmartWork's own. Fixed by only ever trusting a `pubspec.yaml`
/// whose `name:` field is actually `smartwork_cli`.
///
/// Exercises the working-directory fallback via [readSmartworkCliVersion]'s
/// `workingDirectory` parameter rather than mutating the real
/// `Directory.current` (V1 CLI Final Audit — that mutation is
/// process-wide, not isolate-local, so it raced against other
/// concurrently-run test files under `dart test`'s default
/// concurrency). Real callers never pass `workingDirectory` and still
/// get the genuine current working directory.
void main() {
  group('readSmartworkCliVersion', () {
    late Directory tempDir;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('smartwork_version_test_');
    });

    tearDown(() {
      tempDir.deleteSync(recursive: true);
    });

    test(
        'never reports an unrelated project\'s version just because a '
        'pubspec.yaml happens to exist in the current working '
        'directory — the exact bug found running doctor inside a real '
        'generated SmartWork project', () {
      File('${tempDir.path}/pubspec.yaml').writeAsStringSync('''
name: my_generated_app
description: A Flutter project generated by SmartWork.
version: 1.0.0+1
''');

      final version = readSmartworkCliVersion(workingDirectory: tempDir);

      expect(version, isNot('1.0.0+1'));
    });

    test(
        'reports the version from a pubspec.yaml that genuinely '
        'belongs to smartwork_cli', () {
      File('${tempDir.path}/pubspec.yaml').writeAsStringSync('''
name: smartwork_cli
description: CLI interface for Smartwork project generation.
version: 9.9.9
''');

      final version = readSmartworkCliVersion(workingDirectory: tempDir);

      expect(version, '9.9.9');
    });

    test(
        'returns null (never a made-up placeholder) when no '
        'smartwork_cli pubspec.yaml can be found', () {
      final version = readSmartworkCliVersion(workingDirectory: tempDir);

      expect(version, isNull);
    });
  });
}
