import 'dart:convert';
import 'dart:io';

import 'package:dart_mcp/client.dart';
import 'package:dart_mcp/stdio.dart';
import 'package:smartwork_core/smartwork_core.dart';
import 'package:test/test.dart';

import 'e2e_fixture_support.dart';

/// The MCP-3 mandatory acceptance test: a real MCP client talking to a
/// real, separately-spawned `smartwork_mcp` server process over the
/// actual stdio transport, driving `smartwork_target_plan` then
/// `smartwork_target_apply` against a real project generated by the
/// actual SmartWork CLI (Android only) — with no injected fakes, so
/// this exercises the real `flutter create` and real `flutter
/// analyze`/`flutter test` validation pipeline exactly as a real MCP
/// client would experience it.
void main() {
  test(
      'a real client plans then applies Android + iOS against a real '
      'generated project, over real stdio, through a real spawned '
      'server process', () async {
    final packageRoot = Directory.current.path;
    final projectPath = e2eFixturePath('mcp_target_e2e');
    await generateSmartworkFixture(
      projectPath,
      config: ProjectConfig(
        projectName: 'mcp_target_e2e',
        appTargets: {AppTarget.android},
        architecture: Architecture.cleanArchitecture,
        stateManagement: StateManagement.bloc,
        network: Network.http,
        storage: Storage.sharedPreferences,
        initialFeatures: ['home'],
      ),
    );
    addTearDown(() => deleteE2EFixture(projectPath));

    final process = await Process.start(
      'dart',
      ['run', 'bin/smartwork_mcp.dart'],
      workingDirectory: packageRoot,
    );
    addTearDown(() => process.kill());

    final stderrLines = <String>[];
    process.stderr
        .transform(utf8.decoder)
        .transform(const LineSplitter())
        .listen(stderrLines.add);

    final client =
        MCPClient(Implementation(name: 'e2e-client', version: '1.0.0'));
    final connection = client.connectServer(
      stdioChannel(input: process.stdout, output: process.stdin),
    );

    await connection.initialize(InitializeRequest(
      protocolVersion: ProtocolVersion.latestSupported,
      capabilities: ClientCapabilities(),
      clientInfo: Implementation(name: 'e2e-client', version: '1.0.0'),
    ));
    connection.notifyInitialized();

    final tools = await connection.listTools();
    expect(
      tools.tools.map((t) => t.name),
      containsAll(['smartwork_target_plan', 'smartwork_target_apply']),
    );

    final planResult = await connection.callTool(CallToolRequest(
      name: 'smartwork_target_plan',
      arguments: {
        'projectPath': projectPath,
        'appTargets': ['android', 'ios'],
      },
    ));
    expect(planResult.isError, isNot(true));
    final planStructured = planResult.structuredContent!;
    expect(planStructured['changes'], {
      'add': ['ios'],
      'removedFromConfig': <String>[],
    });
    expect(Directory('$projectPath/ios').existsSync(), isFalse,
        reason: 'target_plan must never create files');
    final plan = planStructured['plan'];

    final applyResult = await connection.callTool(CallToolRequest(
      name: 'smartwork_target_apply',
      arguments: {
        'projectPath': projectPath,
        'plan': plan,
        'confirm': true,
      },
    ));
    expect(applyResult.isError, isNot(true),
        reason: 'target_apply failed: ${applyResult.content}');
    final applyStructured = applyResult.structuredContent!;
    expect(applyStructured['success'], isTrue);
    final validationPhases =
        (applyStructured['result'] as Map)['validationPhases'] as List;
    expect(
      validationPhases.every((p) => (p as Map)['passed'] == true),
      isTrue,
      reason: 'validationPhases: $validationPhases',
    );

    await client.shutdown();
    process.kill();
    await process.exitCode;

    // Real filesystem verification.
    expect(Directory('$projectPath/ios').existsSync(), isTrue,
        reason: 'ios/ must now exist');
    expect(Directory('$projectPath/android').existsSync(), isTrue,
        reason: 'android/ must remain');
    final configText =
        File('$projectPath/.smartwork/project.yaml').readAsStringSync();
    expect(configText, contains('android'));
    expect(configText, contains('ios'));

    // SmartWork-generated files remain valid.
    expect(Directory('$projectPath/lib/features/home').existsSync(), isTrue);
    expect(
        File('$projectPath/lib/services/routing/app_router.dart').existsSync(),
        isTrue);
    expect(File('$projectPath/README.md').existsSync(), isTrue);

    final analyze = await Process.run('flutter', ['analyze'],
        workingDirectory: projectPath);
    expect(analyze.exitCode, 0, reason: analyze.stdout.toString());

    final flutterTest =
        await Process.run('flutter', ['test'], workingDirectory: projectPath);
    expect(flutterTest.exitCode, 0, reason: flutterTest.stdout.toString());
  }, timeout: const Timeout(Duration(minutes: 3)));
}
