import 'dart:convert';
import 'dart:io';

import 'package:dart_mcp/client.dart';
import 'package:dart_mcp/stdio.dart';
import 'package:smartwork_core/smartwork_core.dart';
import 'package:test/test.dart';

import 'e2e_fixture_support.dart';

/// The MCP-0/MCP-1 acceptance test: a real MCP client talking to a
/// real, separately-spawned `smartwork_mcp` server process over the
/// actual stdio transport — not a Dart method call, not an in-process
/// channel. Runs against a real project generated by the actual
/// SmartWork CLI, exercising every MCP-1 lifecycle tool and verifying
/// real filesystem effects, then validates the resulting project with
/// real `flutter analyze`/`flutter test` — not source inspection.
void main() {
  final projectPath = e2eFixturePath('mcp_roundtrip');

  setUpAll(() async {
    await generateSmartworkFixture(
      projectPath,
      config: ProjectConfig(
        projectName: 'mcp_roundtrip',
        appTargets: {AppTarget.android},
        architecture: Architecture.cleanArchitecture,
        stateManagement: StateManagement.bloc,
        network: Network.http,
        storage: Storage.sharedPreferences,
        initialFeatures: ['home'],
      ),
    );
  });

  tearDownAll(() => deleteE2EFixture(projectPath));

  test(
      'a real client drives the full doctor + feature + service '
      'lifecycle against a real spawned server process, over real '
      'stdio, against a real generated project', () async {
    final packageRoot = Directory.current.path;
    final process = await Process.start(
      'dart',
      ['run', 'bin/smartwork_mcp.dart'],
      workingDirectory: packageRoot,
    );
    addTearDown(() {
      process.kill();
    });

    final stderrLines = <String>[];
    process.stderr
        .transform(utf8.decoder)
        .transform(const LineSplitter())
        .listen(stderrLines.add);

    final client =
        MCPClient(Implementation(name: 'e2e-client', version: '1.0.0'));
    final connection = client.connectServer(
      stdioChannel(input: process.stdout, output: process.stdin),
    );

    final initResult = await connection.initialize(InitializeRequest(
      protocolVersion: ProtocolVersion.latestSupported,
      capabilities: ClientCapabilities(),
      clientInfo: Implementation(name: 'e2e-client', version: '1.0.0'),
    ));
    expect(initResult.serverInfo.name, 'smartwork_mcp');
    connection.notifyInitialized();

    final tools = await connection.listTools();
    expect(
      tools.tools.map((t) => t.name),
      containsAll([
        'smartwork_doctor',
        'smartwork_feature_add',
        'smartwork_feature_remove',
        'smartwork_service_add',
        'smartwork_service_remove',
      ]),
    );

    // 1. doctor
    final doctorResult = await connection.callTool(CallToolRequest(
      name: 'smartwork_doctor',
      arguments: {'projectPath': projectPath},
    ));
    expect(doctorResult.isError, isNot(true));
    final doctorChecks =
        (doctorResult.structuredContent!['checks'] as List).cast<Map>();
    expect(
      doctorChecks.any(
          (c) => c['label'] == 'SmartWork project' && c['status'] == 'pass'),
      isTrue,
    );

    // 2. feature add
    final addResult = await connection.callTool(CallToolRequest(
      name: 'smartwork_feature_add',
      arguments: {'projectPath': projectPath, 'featureName': 'profile'},
    ));
    expect(addResult.isError, isNot(true));
    expect(addResult.structuredContent!['success'], isTrue);
    expect(
      Directory('$projectPath/lib/features/profile').existsSync(),
      isTrue,
      reason: 'real filesystem effect of feature_add',
    );
    expect(
      File('$projectPath/lib/services/routing/app_router.dart')
          .readAsStringSync(),
      contains("case '/profile':"),
    );

    // 3. service add
    final serviceAddResult = await connection.callTool(CallToolRequest(
      name: 'smartwork_service_add',
      arguments: {'projectPath': projectPath, 'service': 'analytics'},
    ));
    expect(serviceAddResult.isError, isNot(true));
    expect(serviceAddResult.structuredContent!['success'], isTrue);
    expect(
      Directory('$projectPath/lib/services/analytics').existsSync(),
      isTrue,
      reason: 'real filesystem effect of service_add',
    );

    // 4. service remove
    final serviceRemoveResult = await connection.callTool(CallToolRequest(
      name: 'smartwork_service_remove',
      arguments: {'projectPath': projectPath, 'service': 'analytics'},
    ));
    expect(serviceRemoveResult.isError, isNot(true));
    expect(
      Directory('$projectPath/lib/services/analytics').existsSync(),
      isFalse,
      reason: 'real filesystem effect of service_remove',
    );

    // 5. feature remove
    final removeResult = await connection.callTool(CallToolRequest(
      name: 'smartwork_feature_remove',
      arguments: {'projectPath': projectPath, 'featureName': 'profile'},
    ));
    expect(removeResult.isError, isNot(true));
    expect(
      Directory('$projectPath/lib/features/profile').existsSync(),
      isFalse,
      reason: 'real filesystem effect of feature_remove',
    );
    expect(
      File('$projectPath/lib/services/routing/app_router.dart')
          .readAsStringSync(),
      isNot(contains("case '/profile':")),
    );

    await client.shutdown();
    process.kill();
    final exitCode = await process.exitCode;
    expect(exitCode, anyOf(0, -15, 143));

    // The generated project must still be genuinely valid after this
    // whole real add/remove sequence — real flutter analyze/test, not
    // source inspection.
    final analyze = await Process.run(
      'flutter',
      ['analyze'],
      workingDirectory: projectPath,
    );
    expect(analyze.exitCode, 0, reason: analyze.stdout.toString());

    final flutterTest = await Process.run(
      'flutter',
      ['test'],
      workingDirectory: projectPath,
    );
    expect(flutterTest.exitCode, 0, reason: flutterTest.stdout.toString());
  }, timeout: const Timeout(Duration(seconds: 90)));
}
