import 'dart:io';

import 'package:dart_mcp/client.dart';
import 'package:smartwork_core/smartwork_core.dart';
import 'package:smartwork_mcp/smartwork_mcp.dart';
import 'package:stream_channel/stream_channel.dart';
import 'package:test/test.dart';

import 'e2e_fixture_support.dart';

/// Phase 13 of the MCP-3 E2E requirements: meaningful target
/// combinations, each starting from a real Android-only project
/// generated by the actual SmartWork CLI, applied through the real
/// in-process MCP protocol with genuinely unfaked Core classes
/// (`TargetTools()`'s own defaults: a real `FlutterBootstrap`/
/// `ProjectValidator`, so real `flutter create` and real `flutter
/// analyze`/`test` still run). Case A (Android+iOS) is already covered
/// by the mandatory real spawned-process test in
/// real_target_e2e_test.dart.
void main() {
  final cases = [
    (name: 'B', dirName: 'mcp_target_matrix_b', targets: ['android', 'ios']),
    (name: 'C', dirName: 'mcp_target_matrix_c', targets: ['android', 'web']),
    (
      name: 'D',
      dirName: 'mcp_target_matrix_d',
      targets: ['android', 'ios', 'web', 'windows', 'macos', 'linux'],
    ),
  ];

  for (final c in cases) {
    test(
        'Case ${c.name}: ${c.targets.join('+')} — plan then apply '
        'produces a real, valid Flutter project', () async {
      final projectPath = e2eFixturePath(c.dirName);
      await generateSmartworkFixture(
        projectPath,
        config: ProjectConfig(
          projectName: c.dirName,
          appTargets: {AppTarget.android},
          architecture: Architecture.cleanArchitecture,
          stateManagement: StateManagement.bloc,
          network: Network.http,
          storage: Storage.sharedPreferences,
          initialFeatures: ['home'],
        ),
      );
      addTearDown(() => deleteE2EFixture(projectPath));

      final controller = StreamChannelController<String>();
      final server = SmartworkMcpServer(controller.foreign);
      final client =
          MCPClient(Implementation(name: 'matrix-client', version: '1.0.0'));
      final connection = client.connectServer(controller.local);
      await connection.initialize(InitializeRequest(
        protocolVersion: ProtocolVersion.latestSupported,
        capabilities: ClientCapabilities(),
        clientInfo: Implementation(name: 'matrix-client', version: '1.0.0'),
      ));
      connection.notifyInitialized();
      await server.initialized;

      final planResult = await connection.callTool(CallToolRequest(
        name: 'smartwork_target_plan',
        arguments: {'projectPath': projectPath, 'appTargets': c.targets},
      ));
      expect(planResult.isError, isNot(true),
          reason: 'plan failed: ${planResult.content}');
      final plan = planResult.structuredContent!['plan'];

      final applyResult = await connection.callTool(CallToolRequest(
        name: 'smartwork_target_apply',
        arguments: {
          'projectPath': projectPath,
          'plan': plan,
          'confirm': true,
        },
      ));
      expect(applyResult.isError, isNot(true),
          reason: 'apply failed: ${applyResult.content}');
      final validationPhases = ((applyResult.structuredContent!['result']
          as Map)['validationPhases'] as List);
      expect(
        validationPhases.every((p) => (p as Map)['passed'] == true),
        isTrue,
        reason: 'Case ${c.name} validationPhases: $validationPhases',
      );

      await client.shutdown();
      await server.shutdown();

      for (final target in c.targets) {
        expect(Directory('$projectPath/$target').existsSync(), isTrue,
            reason: 'Case ${c.name}: $target/ must exist');
      }

      // Independent real Flutter validation, not just trusting
      // apply's own internal report.
      final analyze = await Process.run('flutter', ['analyze'],
          workingDirectory: projectPath);
      expect(analyze.exitCode, 0, reason: analyze.stdout.toString());

      final flutterTest =
          await Process.run('flutter', ['test'], workingDirectory: projectPath);
      expect(flutterTest.exitCode, 0, reason: flutterTest.stdout.toString());
    }, timeout: const Timeout(Duration(minutes: 3)));
  }
}
